export const PLUGIN_ID = 'touch_portal_star_citizen_tools';
export const SC_ROOT_PATH = 'Star Citizen Root Directory';
export const SC_ENVIRONMENT = 'Star Citizen Environment';
export const SC_GAME_LOG_FILE = 'Star Citizen Game Log File';
export const SC_READ_LOG_INTERVAL = 'Star Citizen Read Interval';
export const SC_BLACKLIST = 'Star Citizen Blacklist';
export const UPDATE_URL = 'https://raw.githubusercontent.com/BluntlyCat/TouchPortal-SCLogEventHandler/refs/heads/main/base/entry.tp';
export const RELEASE_URL = 'https://raw.githubusercontent.com/BluntlyCat/TouchPortal-SCLogEventHandler/releases';
export const TIMESTAMP_REGEX = '<(?<timestamp>\d+-\d+-\d+T\d+:\d+:\d+\.\d+Z)>'
export const PLAYER_VICTIM_REGEX = '\'(?<victim>[A-Za-z0-9_-]+)\'';
export const ZONE_REGEX = '?in zone \'(?<zone>[\\w_-]+)\'';
export const DAMAGE_TYPE_REGEX = '?with damage type \'(?<dmgType>\\w+)\''